[tool.poetry]
name = "arg-monitoring"
version = "0.69.420"
description = "Monitors the ARG and stuff"
authors = ["clueless author <clueless@clueless.org>"]
readme = "../README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
pytube = "^15.0.0"
requests = "^2.31.0"
dataclasses-json = "^0.6.4"
beautifulsoup4 = "^4.12.3"
feedgen = "^1.0.0"
pylint = "*"
mypy = "*"
flake8 = "*"
youtube-dl = { git = "https://github.com/ytdl-org/youtube-dl.git", branch = "master" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
