name: Generate feed

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ./feed-generator

      - name: Restore pickle and json files
        uses: actions/cache/restore@v3
        with:
          path: |
            atom.pickle
            cache.json
          key: ${{ runner.os }}-caches

      - name: Run main.py
        run: |
          python feed-generator/src/main.py

      - name: Cache pickle and json files
        uses: actions/cache/save@v3
        with:
          path: |
            atom.pickle
            cache.json
          key: ${{ runner.os }}-caches

      - name: Add a commit (only if there are changes)
        run: |
          git config --local user.email "worker@github.com"
          git config --local user.name "Feed Worker"
          git stash "generated changes"
          git checkout publish
          git rm atom.xml cache.json
          git stash apply
          git add -f atom.xml cache.json
          git commit -m "Update atom.xml and cache.json" || exit 0

      - name: Push new commit
        if: ${{ !github.event.act }}
        run: |
          git push origin publish
