name: Twitch Stream Trigger

on:
  workflow_dispatch:

jobs:
  handle_trigger:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          lang: ["EN", "JP", "CN"]
    steps:
      - uses: actions/checkout@v4

      - name: Download executable
        working-directory: ./feed-generator/src/sources/twitch_source
        run: |
          wget https://github.com/owobred/pleep/releases/download/latest/pleep-search
          wget https://github.com/neuro-arg/arg-monitoring/releases/download/audio-monitoring-live/out.bin
          chmod +x pleep-search

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache / Restore pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install APT dependencies with cache
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ffmpeg libsm6 libxext6 jq
          version: 1.0

      - name: Install dependencies
        run: |
          python -m pip install --disable-pip-version-check --no-compile ./feed-generator

      - name: Run monitor switch
        env:
          TWITCH_OAUTH: ${{ secrets.TWITCH_OAUTH }}
          MONITOR_SWITCH: ${{ matrix.lang }}
        run: |
          cd feed-generator/src/sources/twitch_source
          ./monitoring.sh || true
          cd -
          cp feed-generator/src/sources/twitch_source/*.txt .

      - name: Stash results
        run: |
          git config --local user.email "worker@github.com"
          git config --local user.name "Twitch Worker"
          git add -f neuro.txt || true
          git add -f evil.txt || true
          git stash -m "generated changes"

      - name: Checkout to publish
        uses: actions/checkout@v4
        with:
          ref: 'publish'

      - name: Add a commit (only if there are changes)
        run: |
          git rm neuro.txt || true
          git rm evil.txt || true
          git stash apply
          git add -f neuro.txt || git checkout HEAD -- neuro.txt || true
          git add -f evil.txt || git checkout HEAD -- evil.txt || true
          git commit -m "Update Twitch TXT" || true
          git log

      - name: Push new commit
        if: ${{ !github.event.act }}
        run: |
          git push origin publish

  call_next_workflow:
    needs: handle_trigger
    uses: ./.github/workflows/generate-feed.yml
    secrets: inherit
